//Excavator
//MineralString + OreString, Chance
mods.immersiveengineering.Excavator.getMineral("Bauxite").removeOre("oreAluminum");
mods.immersiveengineering.Excavator.getMineral("Bauxite").addOre("oreRichBauxite", 1.00);
mods.immersiveengineering.Excavator.getMineral("Cassiterite").removeOre("oreTin");
mods.immersiveengineering.Excavator.getMineral("Cassiterite").addOre("oreRichTin", 0.65);
mods.immersiveengineering.Excavator.getMineral("Cassiterite").addOre("oreCryolite", 0.25);
mods.immersiveengineering.Excavator.getMineral("Cassiterite").addOre("oreRichZinc", 0.10);
mods.immersiveengineering.Excavator.getMineral("Coal").removeOre("oreCoal");
mods.immersiveengineering.Excavator.getMineral("Coal").removeOre("oreDiamond");
mods.immersiveengineering.Excavator.getMineral("Coal").removeOre("oreEmerald");
mods.immersiveengineering.Excavator.getMineral("Coal").addOre("gemAnthracite", 0.70);
mods.immersiveengineering.Excavator.getMineral("Coal").addOre("oreKaolinite", 0.15);
mods.immersiveengineering.Excavator.getMineral("Coal").addOre("oreGraphite", 0.02);
mods.immersiveengineering.Excavator.getMineral("Coal").addOre("oreSaltpeter", 0.03);
mods.immersiveengineering.Excavator.getMineral("Coal").addOre("gemWorkingDiamond", 0.05);
mods.immersiveengineering.Excavator.getMineral("Coal").addOre("gemWorkingEmerald", 0.05);
mods.immersiveengineering.Excavator.getMineral("Copper").removeOre("oreCopper");
mods.immersiveengineering.Excavator.getMineral("Copper").removeOre("oreGold");
mods.immersiveengineering.Excavator.getMineral("Copper").removeOre("oreNickel");
mods.immersiveengineering.Excavator.getMineral("Copper").addOre("oreRichNativeCopper", 0.68);
mods.immersiveengineering.Excavator.getMineral("Copper").addOre("oreRichGold", 0.26);
mods.immersiveengineering.Excavator.getMineral("Copper").addOre("oreRichNickel", 0.06);
mods.immersiveengineering.Excavator.getMineral("Galena").removeOre("oreLead");
mods.immersiveengineering.Excavator.getMineral("Galena").removeOre("oreSilver");
mods.immersiveengineering.Excavator.getMineral("Galena").removeOre("oreSulfur");
mods.immersiveengineering.Excavator.getMineral("Galena").addOre("oreRichLead", 0.45);
mods.immersiveengineering.Excavator.getMineral("Galena").addOre("oreRichSilver", 0.45);
mods.immersiveengineering.Excavator.getMineral("Galena").addOre("oreGraphite", 0.10);
mods.immersiveengineering.Excavator.getMineral("Gold").removeOre("oreGold");
mods.immersiveengineering.Excavator.getMineral("Gold").removeOre("oreCopper");
mods.immersiveengineering.Excavator.getMineral("Gold").removeOre("oreNickel");
mods.immersiveengineering.Excavator.getMineral("Gold").addOre("oreRichGold", 0.68);
mods.immersiveengineering.Excavator.getMineral("Gold").addOre("oreRichTetrahedrite", 0.26);
mods.immersiveengineering.Excavator.getMineral("Gold").addOre("oreRichNickel", 0.06);
mods.immersiveengineering.Excavator.getMineral("Iron").removeOre("oreIron");
mods.immersiveengineering.Excavator.getMineral("Iron").removeOre("oreNickel");
mods.immersiveengineering.Excavator.getMineral("Iron").removeOre("oreTin");
mods.immersiveengineering.Excavator.getMineral("Iron").addOre("oreRichHematite", 0.53);
mods.immersiveengineering.Excavator.getMineral("Iron").addOre("oreRichNickel", 0.26);
mods.immersiveengineering.Excavator.getMineral("Iron").addOre("oreRichTin", 0.21);
mods.immersiveengineering.Excavator.getMineral("Lapis").removeOre("oreLapis");
mods.immersiveengineering.Excavator.getMineral("Lapis").removeOre("oreIron");
mods.immersiveengineering.Excavator.getMineral("Lapis").removeOre("oreSulfur");
mods.immersiveengineering.Excavator.getMineral("Lapis").addOre("oreLapis", 0.65);
mods.immersiveengineering.Excavator.getMineral("Lapis").addOre("oreRichHematite", 0.25);
mods.immersiveengineering.Excavator.getMineral("Lapis").addOre("oreRichMalachite", 0.10);
mods.immersiveengineering.Excavator.getMineral("Lead").removeOre("oreLead");
mods.immersiveengineering.Excavator.getMineral("Lead").removeOre("oreSilver");
mods.immersiveengineering.Excavator.getMineral("Lead").addOre("oreRichLead", 0.55);
mods.immersiveengineering.Excavator.getMineral("Lead").addOre("oreRichSilver", 0.35);
mods.immersiveengineering.Excavator.getMineral("Lead").addOre("oreGraphite", 0.10);
mods.immersiveengineering.Excavator.getMineral("Magnetite").removeOre("oreGold");
mods.immersiveengineering.Excavator.getMineral("Magnetite").removeOre("oreIron");
mods.immersiveengineering.Excavator.getMineral("Magnetite").addOre("oreRichMagnetite", 0.65);
mods.immersiveengineering.Excavator.getMineral("Magnetite").addOre("oreRichGold", 0.20);
mods.immersiveengineering.Excavator.getMineral("Magnetite").addOre("oreRichBismuth", 0.15);
mods.immersiveengineering.Excavator.getMineral("Nickel").removeOre("oreNickel");
mods.immersiveengineering.Excavator.getMineral("Nickel").removeOre("oreIron");
mods.immersiveengineering.Excavator.getMineral("Nickel").addOre("oreRichNickel", 0.90);
mods.immersiveengineering.Excavator.getMineral("Nickel").addOre("oreRichPlatinum", 0.05);
mods.immersiveengineering.Excavator.getMineral("Nickel").addOre("oreRichMagnetite", 0.05);
mods.immersiveengineering.Excavator.getMineral("Platinum").removeOre("oreNickel");
mods.immersiveengineering.Excavator.getMineral("Platinum").addOre("oreRichPlatinum", 0.40);
mods.immersiveengineering.Excavator.getMineral("Platinum").addOre("oreRichNickel", 0.15);
mods.immersiveengineering.Excavator.getMineral("Platinum").addOre("oreRichArdite", 0.05);
mods.immersiveengineering.Excavator.getMineral("Platinum").addOre("oreNormalArdite", 0.10);
mods.immersiveengineering.Excavator.getMineral("Platinum").addOre("oreRichCobalt", 0.05);
mods.immersiveengineering.Excavator.getMineral("Platinum").addOre("oreNormalCobalt", 0.10);
mods.immersiveengineering.Excavator.getMineral("Platinum").addOre("oreMithril", 0.15);
mods.immersiveengineering.Excavator.getMineral("Pyrite").removeOre("oreIron");
mods.immersiveengineering.Excavator.getMineral("Pyrite").removeOre("oreSulfur");
mods.immersiveengineering.Excavator.getMineral("Pyrite").addOre("oreRichLimonite", 0.50);
mods.immersiveengineering.Excavator.getMineral("Pyrite").addOre("oreSulfur", 0.50);
mods.immersiveengineering.Excavator.getMineral("Silver").removeOre("oreSilver");
mods.immersiveengineering.Excavator.getMineral("Silver").removeOre("oreLead");
mods.immersiveengineering.Excavator.getMineral("Silver").addOre("oreRichSilver", 0.58);
mods.immersiveengineering.Excavator.getMineral("Silver").addOre("oreRichLead", 0.42);
mods.immersiveengineering.Excavator.getMineral("Uranium").removeOre("oreLead");
mods.immersiveengineering.Excavator.getMineral("Uranium").removeOre("oreUranium");
mods.immersiveengineering.Excavator.getMineral("Uranium").addOre("oreUranium", 0.45);
mods.immersiveengineering.Excavator.getMineral("Uranium").addOre("oreRichLead", 0.25);
mods.immersiveengineering.Excavator.getMineral("Uranium").addOre("oreRichYellorite", 0.10);
mods.immersiveengineering.Excavator.getMineral("Uranium").addOre("oreNormalYellorite", 0.20);